### ISSUE TITLE
Is this book public?

### ISSUE THREAD

**Issue by manuel-delverme** [openworm/worm-math-book#5]
This seems something I would be interested in following, but I'm not sure where to start from.
Is the project published or WIP?

**Comment by VahidGh** [comment]
Hey @manuel-delverme 
Actually, it is still in an examination phase :)
Would be great if you could take a look into ideas and discussions over here:
https://github.com/openworm/worm-math-book/discussions
And let us know about your interest areas on this thread:
https://github.com/openworm/worm-math-book/discussions/6
